POST http://localhost:5000/users
Content-Type: application/json

{
    "username":"aids",
    "password": "aids"
}

### 
POST http://localhost:5000/authenticate
Content-Type: application/json

{
    "username":"aids",
    "password": "aids"
}

###


GET http://localhost:5000/users

###

GET http://localhost:5000/token

###

PUT  http://localhost:5000/users/5

Content-Type: application/json

{
    "username":"yeet",
    "password": "yeet"
}
