POST http://localhost:5000/users
Content-Type: application/json

{
    "firstname":"vadim",
    "lastname": "real"
}

### 

GET http://localhost:5000/users

###

PUT  http://localhost:5000/users/5

Content-Type: application/json

{
    "firstname":"yeet",
    "lastname": "yeet"
}
