POST http://localhost:5000/users
Content-Type: application/json

{
    "username":"yeet",
    "password": "yeet"
}

### 

GET http://localhost:5000/users

###

PUT  http://localhost:5000/users/5

Content-Type: application/json

{
    "username":"yeet",
    "password": "yeet"
}
